apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile-de-crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mobile-de-crawler
  template:
    metadata:
      labels:
        app: mobile-de-crawler
    spec:
      nodeSelector:
        kubernetes.io/hostname: rserver
      initContainers:
        - name: rabbitmq-wait
          image: busybox:1.35.0-uclibc
          command:
            - /bin/sh
            - -c
            - |
              until nc -z rabbitmq-service.mobile-de-data-collector.svc.cluster.local 15672; do
                  echo waiting for rabbitmq-service; sleep 2;
              done
      containers:
        - name: mobile-de-crawler
          image: localhost:5000/com.robertciotoiu/mobile-de-crawler:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_RABBITMQ_HOST
              value: rabbitmq-service
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_RABBITMQ_USERNAME
              value: guest
            - name: SPRING_RABBITMQ_PASSWORD
              value: guest

            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb-service
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_USERNAME
              value: admin
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: admin
            - name: SPRING_DATA_MONGODB_DATABASE
              value: mobile-de-car-data
            - name: management.endpoint.health.probes.enabled
              value: "true"
            - name: management.health.livenessState.enabled
              value: "true"
            - name: management.health.readinessState.enabled
              value: "true"