# XPath to extract each HTML tag containing the listing
listing.xpath=span[data-testid^=result-listing-]

# XPaths to extract each field matching fields from FlatListing class
listingId.xpath=//div[@data-testid='result-listing-1']/@data-testid
title.xpath=//h2[@class='QeGRL']
category.xpath=//div[@data-testid='listing-details-attributes']/div[contains(text(), '?')]/preceding-sibling::strong
scrapeTime.xpath=//meta[@property='og:updated_time']/@content
url.xpath=//a[@data-testid='result-listing-image-1']/@href
imgUrl.xpath=//img[@data-testid='result-listing-image-1']/@src
isNew.xpath=//span[contains(@class, 'NEW')]
isElectric.xpath=//div[contains(text(), 'Electric')]
postedDate.xpath=//div[@data-testid='listing-details-attributes']/div[contains(text(), 'FR')]
registrationDate.xpath=//div[@data-testid='listing-details-attributes']/div[contains(text(), 'FR')]
mileage.xpath=//div[@data-testid='listing-details-attributes']/div[contains(text(), 'km')]
kw.xpath=//div[@data-testid='listing-details-attributes']/div[contains(text(), 'kW')]
hp.xpath=//div[@data-testid='listing-details-attributes']/div[contains(text(), 'hp')]
type.xpath=//div[@data-testid='listing-details-attributes']/div[contains(text(), '?')]/following-sibling::div
status.xpath=//div[@data-testid='listing-details-attributes']/div[contains(text(), '?')]/following-sibling::div
fuel.xpath=//div[@data-testid='listing-details-attributes']/div[contains(text(), 'Petrol') or contains(text(), 'Diesel')]
gearbox.xpath=//div[@data-testid='listing-details-attributes']/div[contains(text(), 'Automatic') or contains(text(), 'Manual')]
hu.xpath=//div[@data-testid='listing-details-attributes']/div[contains(text(), 'HU')]
doors.xpath=//div[@data-testid='listing-details-attributes']/div[contains(text(), 'doors')]
consumption.xpath=//div[@data-testid='listing-details-attributes']/div[contains(text(), 'l/100 km')]
emissions.xpath=//div[@data-testid='listing-details-attributes']/div[contains(text(), 'g/km')]
dealerName.xpath=//div[@data-testid='seller-info']/div/span[@class='rjHf7 Ssf9m']
dealerRating.xpath=//div[@data-testid='seller-info']/div/span[@class='CaPWA']/svg[@class='NDlcw YgmFC']/@aria-label
ratings.xpath=//div[@data-testid='seller-info']/div/span[@class='W9v_K']
location.xpath=//div[@data-testid='seller-info']/div[contains(text(), ',')]
sellerType.xpath=//div[@data-testid='seller-info']/div[contains(text(), 'Private Seller') or contains(text(), 'Dealer')]
price.xpath=//span[@data-testid='price-label']
currency.xpath=//span[@data-testid='price-label']/text()[1]
vehicleExtras.xpath=//div[@data-testid='listing-details-attributes']/div[contains(text(), '?')]/following-sibling::div